esap/esap/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('esap-api/query/', include('query.api.urls')),
    path('esap-api/rucio/', include('rucio.api.urls')),
    path('esap-api/accounts/', include('accounts.api.urls')),
    path('esap-api/ida/', include('ida.api.urls')),
    path('esap-api/batch/', include('batch.api.urls')),
    path('esap-api/admin/', admin.site.urls, name='admin-view'),
    path("esap-api/uws/", include("uws.urls")),
    path("sdc-portal/", include("sdc_portal.urls")),
    re_path('^esap-api/oidc/', include('mozilla_django_oidc.urls')),
]

esap/sdc_portal/urls.py
from django.urls import path

from . import views

app_name = "sdc_portal"

urlpatterns = [
    path("", views.home, name="home"),
    path("signin", views.signin, name="signin"),
    path("logout", views.logout, name="logout"),
    path("search", views.search, name="search"),
]

esap/sdc_portal/models.py
from django.db import models

# Create your models here.

esap/sdc_portal/forms.py
'''
Created on 2023-09-14
Class to define forms
@author: renaud.savalle@obspm.fr
'''

from django import forms


class DemoForm(forms.Form):

    target_raj2000_desc = 'Right Ascension of target in deg (J2000)'
    target_raj2000 = forms.DecimalField(
        label='Target RA (deg):', required = True,
        help_text=target_raj2000_desc,
        widget=forms.NumberInput(attrs={
                                      'placeholder': target_raj2000_desc,
                                      'class': 'form-control form-control-sm',
                                      }),
        min_value=0.0, max_value=360.0,
    )

    target_dej2000_desc = 'Declination of target in deg (J2000)'
    target_dej2000 = forms.DecimalField(
        label='Target DEC (deg):', required = True,
        help_text='Declination of target in deg (J2000)',
        widget=forms.NumberInput(attrs={
                                      'placeholder': target_dej2000_desc,
                                      'class': 'form-control form-control-sm',
                                      }),
        min_value=(-90.0), max_value=90.0,
    )

    search_radius_desc = 'Cone Search radius in deg.'
    search_radius = forms.DecimalField(
        label='Cone Search Radius (deg):', required = True,
        help_text=search_radius_desc,
        widget=forms.NumberInput(attrs={
                                        'placeholder': search_radius_desc,
                                        'class': 'form-control form-control-sm',
                                        }),
        min_value=0.0, max_value=90.0,
    )

esap/sdc_portal/views.py
from django.contrib import messages
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse

import logging
import json

from django.utils.http import urlencode

from .forms import DemoForm
from .fieldstore import FieldStore
from .tap import Tap, convert_astropy_table_to_array

logger = logging.getLogger('query')

def home(request):
    return render(request, "sdc_portal/home.html")


def signin(request):
    return redirect(reverse('oidc_authentication_init'))


def logout(request):
    return redirect(reverse('oidc_logout'))


def search(request):
    '''
    basic search interface
    '''

    logger.info('search view')

    json_dt_data = ''
    json_dt_cols = ''

    store = FieldStore()

    fields = store.get_fields()

    # init fields to their default values
    for field in fields.values():
        field['value'] = field['default']

    logger.info(fields)


    # To work the same way with GET or POST
    args=None
    if request.method == 'POST': # If form was posted
        args=request.POST

    if request.method == 'GET':
        args=request.GET

    logger.info('args={}'.format(args))

    if len(args) != 0:  # some parameters where passed


        # Create a form from the posted data
        demo_form = DemoForm(args)

        if demo_form.is_valid():

            logger.info('demo_form is valid')

            logger.info(demo_form.cleaned_data)

            # set the value of the field according to what's found in the cleaned form
            for k in fields.keys():
                fields[k]['value'] = demo_form.cleaned_data[k]

            if True:

                # (args.get('submit')):  # Button submit was clicked to post the form

                logger.info("Submit button was clicked")

                tap_error, res_table = perform_query(fields)


                if tap_error == None:

                    colnames = res_table.fieldnames
                    logger.info(colnames)

                    # convert res_table (pyvo table) into an array
                    logger.info('Converting pyvo table to json string')
                    rows = convert_astropy_table_to_array(res_table)



                    #nb_rows = len(rows)


                    # prepare data for datatables
                    dt_data = rows

                    dt_cols = []
                    for c in colnames:
                        dt_cols.append({"title": c})



                    json_dt_data = json.dumps(dt_data, cls=DjangoJSONEncoder)
                    json_dt_cols = json.dumps(dt_cols, cls=DjangoJSONEncoder)

                else:
                    messages.error(request,tap_error)


        else:  # form is not valid
            logger.info(demo_form.errors.as_data())
            messages.error(request, 'Error(s) in form: {} Please correct form'.format(demo_form.errors.as_data()))

    # Create form for params, fill it with initial values or values got from POSTed form
    # NB: some field's values be None as number coming from cleaned_data => change None to ''
    initial = {}
    for k in fields.keys():
        initial[k] = '' if fields[k]['value'] is None else fields[k]['value']
    logger.info(initial)

    demo_form = DemoForm(
        auto_id=True,
        initial=initial,
    )


    context = {
        'demo_form': demo_form,
        'json_dt_data': json_dt_data,
        'json_dt_cols': json_dt_cols,
    }

    #logger.info('context={}'.format(context))

    return render(request, 'sdc_portal/search.html', context)



def perform_query(fields):
    '''
    Perform TAP query and returns TAP error (None if OK) and result table
    '''

    logger.info(fields)

    #TODO: move config to dedicated settings variables

    # URL of TAP server
    url='http://voparis-tap-he.obspm.fr/tap'

    # Name of obscore table on the TAP server
    obscore_table = 'hess_dr.obscore_sdc'

    # timeout for TAP server connection
    timeout = 5


    t = Tap(url)

    logger.info('Connecting, timeout={} secs'.format(timeout))
    t.connect(timeout)



    # construct ADQL query - here a conesearch
    query = ("SELECT TOP 100 * FROM {} WHERE 1=CONTAINS(POINT('ICRS',s_ra,s_dec),CIRCLE('ICRS',{},{},{}))".format(
       obscore_table,
       fields['target_raj2000']['value'],
       fields['target_dej2000']['value'],
       fields['search_radius']['value']))



    logger.info('Sending query={} to url={} with timeout={}'.format( query, url, timeout))
    exception, res_table = t.query(query)

    if (exception == None):

        logger.info('No exception, got res_table with {} rows'.format(len(res_table)))

        #print(res_table)

        error = None
    else:
        # try to get exception name
        exception_s = str(exception)
        if exception_s == '':  # happens with TimeoutException
            exception_s = type(exception).__name__

        error = 'Got exception with TAP query: {}'.format(exception_s)
        logger.info('TAP Error: {}'.format( error))


    return error, res_table

esap/sdc_portal/templates/sdc_portal/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		{% block title %}{% endblock%}
		<!-- CSS common-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bootstrap5.min.css' %}"/>
		<link rel="stylesheet" type="text/css" href="https://aladin.u-strasbg.fr/AladinLite/api/v2/latest/aladin.min.css" />
		<!-- CSS local-->{% block css %}{% endblock %}
		<!-- JavaScript common -->
		<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
		<!-- JavaScript local -->{% block js %}{% endblock %}
	</head>

	<body>

		<!-- Variables defined in div elements for JavaScript -->
		<div id="variables">
			<!-- <div id="varname" style="display:none" value="{{ varvalue }}"></div> -->
			<!-- Other variables for the page -->{% block variables %}{% endblock %}
		</div>

		<div id="loading_div"
			 style="position: fixed; top:5px; left:5px; width:2%; z-index: 10; opacity: 0.8;">
			<div id="loading" class="col-md-12" style="display:none;">
				<img src="{% static 'images/loading.png' %}" alt="loading" height="50" width="50"/>
			</div>
		</div>

		<div id="messages_div"
         style="position: fixed; top:40px; left:30%; width:40%; z-index: 10; text-align: center; opacity: 0.8;">
			{% bootstrap_messages %}
		</div>

		<header>
			<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="header">
				<a class="navbar-brand ms-3" href="{% url 'sdc_portal:home' %}">
					CTAO SDC Portal
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#barre" aria-controls="barre" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse" id="barre">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'sdc_portal:home' %}">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'sdc_portal:search' %}">Search</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Profile</a>
						</li>
					</ul>
{% if user.is_authenticated %}
						<a class="btn btn-outline-light nav-link me-2" href="{% url 'sdc_portal:logout' %}">
							Sign out <strong>{{ user.email }}</strong>
						</a>
{% else %}
						<a class="btn btn-outline-light nav-link me-2" href="{% url 'sdc_portal:signin' %}">
							Sign in
						</a>
{% endif %}
				</div>
			</nav>
		</header>

		<main>
			<div class="container">
				{% block content %}
				{% endblock %}
			</div>
		</main>

		<hr>
		<div class="bs-docs-footer">
			<div class="container">
				<p class="page-header"></p>
				<p class="text-center">
					Based on
					<a class="black" href="https://www.djangoproject.com/" target="_blank">
						Django</a>,
					<a class="black" href="http://jquery.com/" target="_blank">
						jQuery</a>
					and
					<a class="black" href="http://getbootstrap.com/" target="_blank">
						Bootstrap</a>.
				</p>
			</div> <!-- container -->
		</div> <!-- footer -->

	</body>

	{% block scripts %}{% endblock %}

</html>

esap/sdc_portal/templates/sdc_portal/home.html
{% extends 'sdc_portal/base.html' %}
{% load static %}


{% block title %}<title>CTAO SDC Portal</title>{% endblock %}

{% block content %}
        <div class="row">
        	<div class="col-md-6">
		        <p>Test page</p>
			</div> <!-- col -->
        	<div class="col-md-6">
            	<p></p>
			</div> <!-- col -->
		</div> <!-- row -->


{% endblock %}

esap/sdc_portal/templates/sdc_portal/search.html
{% extends 'sdc_portal/base.html' %}
{% load static %}

{% block title %}<title>CTAO SDC Portal Demo Search Form</title>{% endblock %}

{% block content %}

    <script type="text/javascript">   

        $(document).ready(function () { // called at page init
            if ('{{ json_dt_data|safe }}' != '') {

                // get data and column info from context
                var data = {{ json_dt_data|safe }};
                var cols = {{ json_dt_cols|safe }};

                console.log("all cols:", cols);

                for (var i = 0; i < cols.length; i++) {
                    if (cols[i].title == 'access_url') {                    
                        console.log(cols[i].title);

                        for (var j = 0; j < data.length; j++) {
                            data[j][i] = '<a class="accessURL" target="_blank">' + data[j][i] + '</a>';
                        }
                    }
                }


                // construct datatable
                dt = new DataTable('#demo_datatable', {
                    data: data,
                    columns: cols,
                    dom: 'ts',
                    scrollX: true,    // allow horizontal scrolling
                });
            }
        });


        $('#demo_datatable').ready(function() {
            const errorModal = new bootstrap.Modal('#error-modal');
            const responseStatusCheck = (response) => {
                if (response.status === 401) {
                    throw "Please, log in to download files!";
                }
                return response;
            }

            $('.accessURL').click(function() {
                url = $(this).text();

                fileName = url.split('/').pop()
                url = "https://dcache-dev.ctaodc.ch:2880/sdc-data/" + fileName;

                fetch("/esap-api/accounts/user-profiles/?format=json", {
                    method: 'GET'
                })
                .then(responseStatusCheck)
                .then((response) => response.json())
                .then(async (json) => {
                    if (!json.results?.length) {
                        throw "Please, log in to download files!";
                    }

                    token = json.results[0].oidc_access_token;

                    return await fetch(url, {
                        method: 'GET',
                        headers: {
                            Authorization: `Bearer ${token}`
                        }
                    });
                })
                .then(responseStatusCheck)
                .then((response) => response.blob())
                .then((blob) => {
                    const a = document.createElement("a");
                    if(blob.type === "") {
                        blob = blob.slice(0, blob.size, "attachment/plain");
                    }
                    a.href = URL.createObjectURL(blob);
                    a.download = fileName;
                    a.click();
                    URL.revokeObjectURL(url);
                })
                .catch((err)=> {
                    if (typeof(err) !== "string"){
                        err = "Impossible to download files right now. Please retry later!";
                    }
                    $('#error-message').text(err);
                    errorModal.show();
                })
            })
        })

    </script>


    <!-- Page JS -->
    <script type="text/javascript" src="{% static 'js/form.js' %}"></script>





    {# Demo form #}
    <form id="demo_form" action="{% url 'sdc_portal:search' %}" method="POST">

        {% csrf_token %}






        {# The form #}
        <div class="panel-group" role="tablist" aria-multiselectable="true" id="demo_form_div" >



            <div id="card-02"> {# position-related fields #}

                    <div class="card">

                        <div class="card-header">
                             <a class="card-link" data-toggle="collapse" data-parent="#card-02" href="#card-element-02">Position</a>
                        </div>

                        <div id="card-element-02" class="collapse show">

                            <div class="card-body">

                                {% for field in demo_form %}

                                    {% if field.name in 'target_raj2000, target_dej2000, search_radius' %}

                                    <div class="form-group{%if field.errors%} has-error{%endif%}">
                                        <label for="{{field.id_for_label}}">
                                            <abbr id="{{field.html_name}}_help" title="{{field.help_text}}">
                                                {{field.label}}
                                            </abbr>
                                        </label>
                                        <br>
                                        <div class="input-group">
                                            {{field}}
                                            {% if field.name in 'target_raj2000, target_dej2000, search_radius' %}
                                                <div class="input-group-append">
                                                <button type="button" onclick="javascript:{{field.name}}.value=''" class="btn btn-outline-secondary">X</button>
                                                </div>
                                            {% endif %}



                                            {%if field.errors%}
                                                <strong class="help-block">{{field.errors}}</strong>
                                            {%endif%}

                                        </div>
                                    </div>
                                    {% endif %}

                                {% endfor %}

                            </div>
                        </div> {# card-element #}
                </div> {#  card #}
            </div> {# card-02 #}

        </div> {# demo_form_div #}




        <br>


        {# Submit buttons #}
        <button type="submit" onclick="cb_submit();" name="submit" class="btn btn-primary">Submit</button>

    </form>

    <div id="results_div" >

        <br>

        {# the datatable #}
        <table id="demo_datatable" class="table table-bordered table-striped datatable nowrap" style="width:100%">

        </table>


    </div>
    <div class="modal" tabindex="-1" id="error-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Error</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p id="error-message">Unable to download files right now. Please retry later!</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
      </div>
      




{% endblock %}